export const initialData = {
  patientName: "",
  gender: "male",
  age: "",
  occupation: "",
  contact: "",
  email: "",
  idProof: "",
  weight: "",
  height: "",
  complaint: "",
  bloodGroup: "",
  referredTo: "",
  address: {
    state: "",
    village: "",
    pin_code: "",
  },
  image: "",
};
